config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }, presence: true
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :list_avatar
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

  def show
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :list_avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container text-center">
  <h1>Add a new bookmark to <%= @list.name %>:</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.all, label_method: :title, value_method: :id, prompt: "Select a Movie to add to this list!" %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
  <br>
  <br>
  <p><%= link_to "Back to #{@list.name}", lists_path %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container1 align-center">
<h1>Our movie lists 💗</h1>

<ul>
  <% @lists.each do |list| %>
    <li>
      <%= link_to list.name, list_path(list) %>
      <%= link_to list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
        <i class="fa-regular fa-trash-can"></i>
      <% end %>
      <% if list.list_avatar.attached? %>
        <%= cl_image_tag list.list_avatar.key, height: 100, width: 100, crop: :fill %>
      <% else %>
        <p>No avatar given</p>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Create a new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<h1>Create a new list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :list_avatar, as: :file %>
  <%= f.submit %>
  <% end %>
  <p><%= link_to "Back to lists", lists_path %></p>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><%= link_to "Bookmark a movie in #{@list.name}", new_list_bookmark_path(@list) %></p>
<br>
<% if @list.list_avatar.attached? %>
        <%= cl_image_tag @list.list_avatar.key, height: 300, width: 400, crop: :fill %>
      <% else %>
        <p>No avatar given</p>
      <% end %>
<ol>
  <% @list.bookmarks.each do |bookmark| %>
    <li>
      <%= bookmark.movie.title %>
      <%= link_to list_bookmark_path(@list, bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
        <i class="fa-regular fa-trash-can"></i>
     <% end %>
    </li>
  <% end %>
</ol>
<br>
<br>
<p><%= link_to "Back to lists", lists_path %></p>